/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectUTS;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.sql.DriverManager;

/**
 *
 * @author Nidzzz
 */
public class FramePembelian extends javax.swing.JFrame {

    Statement stmt;
    PreparedStatement pstmt = null;
    private Connection conn;
    private int idcat;
    private double harga;
    private String namaCAT;
    private String nama;
    private String nik;
    private String email;
    private String telp;
    private List<Object[]> transaksiSementara = new ArrayList<>();

    /**
     * Creates new form FramePembelian
     */
    public FramePembelian(String nama, String nik, String email, String telp) {
        initComponents();
        setTitle("I-FEST TICKET");
        loadComboBoxData();
        this.nama = nama;
        this.nik = nik;
        this.email = email;
        this.telp = telp;
        lbUcapan.setHorizontalAlignment(SwingConstants.CENTER);

        date();

        tfnik.setText(nik);
        tfnama.setText(nama);
        tfemail.setText(email);
        tftelp.setText(telp);
    }

    private void loadComboBoxData() {
        try {
            conn = DBConnection.getConnection();
            conn.setAutoCommit(false);
            cbList.removeAllItems();

            String sql = "SELECT idCAT, namaCAT, harga, kapasitas FROM DaftarCAT ORDER BY idCAT;";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("idCAT");
                String nama = rs.getString("namaCAT");
                String harga = rs.getString("harga");
                int kapasitas = rs.getInt("kapasitas");

                if (kapasitas > 0) {
                    cbList.addItem(nama + "  |  " + harga + "  |  " + kapasitas);
                }
            }

            rs.close();
            pstmt.close();
            conn.close();

        } catch (SQLException e) {
            try {
                if (conn != null) {
                    conn.rollback();
                }
                throw e;
            } catch (SQLException ex) {
                Logger.getLogger(BuatAkun.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void date() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date tanggalSekarang = new Date();
                SimpleDateFormat tanggalWaktu = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                String tanggal = tanggalWaktu.format(tanggalSekarang);
                lbTanggal.setText(tanggal);
            }
        });

        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUcapan = new javax.swing.JLabel();
        lbTanggal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfnik = new javax.swing.JTextField();
        tfnama = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        tftelp = new javax.swing.JTextField();
        cbList = new javax.swing.JComboBox<>();
        tfJumlah = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbUcapan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbUcapan.setText("PEMBELIAN TIKET");
        lbUcapan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbTanggal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTanggal.setText("TANGGAL DAN WAKTU");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("NIK:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("NAMA:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("EMAIL:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("TELEPON:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("KATEGORI:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("JUMLAH:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("TOTAL:");

        tfnik.setEditable(false);
        tfnik.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tfnama.setEditable(false);

        tfemail.setEditable(false);

        tftelp.setEditable(false);

        cbList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListActionPerformed(evt);
            }
        });

        tfJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahActionPerformed(evt);
            }
        });

        tfTotal.setEditable(false);
        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(76, 175, 80));
        jButton1.setText("BELI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("PROFILE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("KEMBALI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(lbUcapan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTanggal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tftelp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                .addComponent(tfemail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfnama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfnik, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbList, javax.swing.GroupLayout.Alignment.LEADING, 0, 257, Short.MAX_VALUE)))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbUcapan)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTanggal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tftelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            conn = DBConnection.getConnection();
            conn.setAutoCommit(false);
            String sql = "SELECT * FROM pembeli where nik = ?";
            pstmt = conn.prepareStatement(sql);
            String nik = tfnik.getText().trim();

            pstmt.setString(1, nik);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                String NIK = rs.getString("nik");
                String email = rs.getString("email");
                String nama = rs.getString("nama");
                String telp = rs.getString("no_telp");
                FrameUbah p = new FrameUbah(NIK, nama, email, telp);
                p.setVisible(true);
                this.setVisible(false);
            }
        } catch (SQLException e) {
            try {
                if (conn != null) {
                    conn.rollback();
                }
                throw e;
            } catch (SQLException ex) {
                Logger.getLogger(BuatAkun.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListActionPerformed
        String selectedItem = (String) cbList.getSelectedItem();
        if (selectedItem != null && selectedItem.contains("|")) {
            String[] parts = selectedItem.split("\\|");
            if (parts.length == 3) {
                namaCAT = parts[0].trim();
                harga = Double.parseDouble(parts[1].trim());
                String kapasitas = parts[2].trim();
            }
        }

        int selectedIndex = cbList.getSelectedIndex();
        switch (selectedIndex) {
            case 0:
                idcat = 1;
                namaCAT = "Festival";
                break;
            case 1:
                idcat = 2;
                namaCAT = "CAT 1";
                break;
            case 2:
                idcat = 3;
                namaCAT = "CAT 2";
                break;
            case 3:
                idcat = 4;
                namaCAT = "CAT 3";
                break;
            case 4:
                idcat = 5;
                namaCAT = "CAT 4";
                break;
            case 5:
                idcat = 6;
                namaCAT = "CAT 5";
                break;
            default:
                idcat = -1;
                break;
        }
    }//GEN-LAST:event_cbListActionPerformed


    private void cbListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cbListAncestorAdded

    private void tfJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahActionPerformed
        String selectedItem = (String) cbList.getSelectedItem();
        if (selectedItem != null) {
            String[] parts = selectedItem.split("  \\|  ");
            if (parts.length == 3) {
                String hargaString = parts[1];
                try {
                    double harga = Double.parseDouble(hargaString);
                    int jumlah = Integer.parseInt(tfJumlah.getText());
                    double total = harga * jumlah;
                    tfTotal.setText(String.valueOf(total));
                } catch (NumberFormatException e) {
                    tfTotal.setText("Invalid Input");
                }
            }
        }
    }//GEN-LAST:event_tfJumlahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            conn = DBConnection.getConnection();
            conn.setAutoCommit(false);

            if (tfJumlah.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Isi semua!");
            } else {
                String jumlah = tfJumlah.getText().trim();
                int jumlahTiket = Integer.parseInt(jumlah);

                String cat = cbList.getSelectedItem().toString();

                String checkKapasitasSql = "SELECT kapasitas FROM DaftarCAT WHERE idCAT = ?";
                PreparedStatement checkKapasitasPstmt = conn.prepareStatement(checkKapasitasSql);
                checkKapasitasPstmt.setInt(1, idcat);
                ResultSet rs = checkKapasitasPstmt.executeQuery();

                if (rs.next()) {
                    int kapasitas = rs.getInt("kapasitas");
                    if (jumlahTiket > kapasitas) {
                        JOptionPane.showMessageDialog(null, "Jumlah tiket yang ingin dibeli melebihi kapasitas yang tersedia!");
                        conn.rollback();
                        return;
                    }
                }

                String sql = "INSERT INTO Transaksi (idCAT, nik, jumlah_tiket, total_harga, tanggalPembelian, harga) VALUES (?,?,?,?,?,?)";
                pstmt = conn.prepareStatement(sql);

                String nik = tfnik.getText().trim();
                String hartot = tfTotal.getText();
                Timestamp timestamp = new Timestamp(System.currentTimeMillis());
                String nama = tfnama.getText();

                pstmt.setInt(1, idcat);
                pstmt.setString(2, nik);
                pstmt.setLong(3, jumlahTiket);
                pstmt.setBigDecimal(4, new BigDecimal(hartot));
                pstmt.setTimestamp(5, timestamp);
                pstmt.setBigDecimal(6, new BigDecimal(harga));

                // Konfirmasi sebelum menambahkan tiket
                String pesan = "Apakah Anda yakin ingin menambahkan tiket?\n"
                        + "Nama Pembeli: " + nama + "\n"
                        + "NIK Pembeli: " + nik + "\n"
                        + "Kategori: " + cat + "\n"
                        + "Jumlah: " + jumlah + "\n"
                        + "Total Harga: " + hartot;

                int jawab = JOptionPane.showConfirmDialog(null, pesan, "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                switch (jawab) {
                    case JOptionPane.YES_OPTION:
                        pstmt.executeUpdate();

                        String updateKapasitasSql = "UPDATE DaftarCAT SET kapasitas = kapasitas - ? WHERE idCAT = ?";
                        PreparedStatement updateKapasitasPstmt = conn.prepareStatement(updateKapasitasSql);
                        updateKapasitasPstmt.setInt(1, jumlahTiket);
                        updateKapasitasPstmt.setInt(2, idcat);
                        updateKapasitasPstmt.executeUpdate();

                        conn.commit();
                        JOptionPane.showMessageDialog(null, "Pembelian berhasil!");

                        tfJumlah.setText("");
                        cbList.setSelectedIndex(0);
                        tfTotal.setText("");
                        loadComboBoxData();
                        break;
                    case JOptionPane.NO_OPTION:
                        break;
                    default:
                        break;
                }
            }
        } catch (SQLException e) {
            try {
                if (conn != null) {
                    conn.rollback();
                }
                throw e;
            } catch (SQLException ex) {
                Logger.getLogger(BuatAkun.class.getName()).log(Level.SEVERE, null, ex);
            }
        } finally {
            try {
                if (conn != null && !conn.isClosed()) {
                    conn.setAutoCommit(true);
                    conn.close();
                }
            } catch (SQLException e) {
                Logger.getLogger(FramePembelian.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FrameMenu p = new FrameMenu(nama, nik, email, telp);
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePembelian("nama", "nik", "email", "telp").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JLabel lbUcapan;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnik;
    private javax.swing.JTextField tftelp;
    // End of variables declaration//GEN-END:variables

}
